web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    TZ: 'Asia/Shanghai'
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.example.com:8929'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
      gitlab_rails['time_zone'] = 'Asia/Shanghai'
      gitlab_rails['smtp_enable'] = true    #启用SMTP，邮件发送服务器必开
      gitlab_rails['smtp_address'] = "smtp.163.com"  # 【163邮件服务器地址】
      gitlab_rails['smtp_port'] = 465 # 启用的端口 ，有人写的是25，但是阿里的会禁用，会报错，所以建议是465，还需要去服务器开启安全策略配置端口
      gitlab_rails['smtp_user_name'] = 'xxxxxx@163.com'
      gitlab_rails['smtp_password'] = "xxxxxxxx"  # 163授权密码 不是163登录密码，建议百度去查
      gitlab_rails['smtp_domain'] = "163.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = true
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
      gitlab_rails['gitlab_email_from'] = 'xxxxxx@163.com' # 发件人邮箱  还有个配置是抄送人邮箱地址，
      user['git_user_email'] = "xxxxxx@163.com"  # 校验什么什么的邮箱 必须和上一个一样
  ports:
    - '8929:8929'
    - '2224:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
